version: 0.1

phases:
  build:
    commands:
      - echo Starting build `date`
      - echo Current directory is `pwd`
      - whereis gradle
      - which gradle
      - chmod +x gradlew
      - ./gradlew build
artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/*
    - '**/*'
  discard-paths: yes