version: 0.1

phases:
  build:
    commands:
      - echo Starting build `date`
      - echo Current directory is `pwd`
      - whereis gradle
      - which gradle
      - chmod +x gradlew
      - ./gradlew build
      - zip demo.zip build/*.jar appspec.yml scripts/*
artifacts:
  files:
    - demo.zip
  discard-paths: yes