version: 0.1

phases:
  build:
    commands:
      - echo Starting build `date`
      - echo Current directory is `pwd`
      - whereis gradle
      - which gradle
      - chmod +x gradlew
      - ./gradlew build
      - mkdir build-output
      - cp build/*.jar appspec.yml scripts/* build-output
      - zip demo.zip build-output/*
      - echo Build completed on `date`
artifacts:
  files:
    - demo.zip
  discard-paths: yes