version: 0.1

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build
artifacts:
  files:
    - build/libs/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
  discard-paths: yes