spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/shoppingDB?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 111111
    url: jdbc:mysql://localhost:3306/shoppingdb?useSSL=false
    username: springuser
    password: Chen1981
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.

okta:
  oauth2:
    issuer: https://dev-433979.okta.com/oauth2/default
    client-id: 0oa36inxodwukffXI4x6
    client-secret: cC1jJdpgHdZ-DTt71F-SfE-l5D3ER02bCh_cX1EO
    groups-claim: groups


